/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);

    }

    @Test 
    public void key() { //debug mode test
        App app = new App();
        Map map = new Map(app);
        assertSame(map.debugMode,false);
        app.key = ' ';
        app.keyPressed();
        assertSame(map.debugMode,false);
        

        
    }
    @Test 
    public void restoreGame() { //test restoreGame, Check if map is restored and move is set to null
        App app = new App();
        Map map = new Map(app);
        app.restartGame();
        assertSame(map.move,null);
        

        
    }
    @Test 
    public void drawTest() { //test restoreGame, Check if map is restored and move is set to null
        App app = new App();
        
        Exception exception = assertThrows(NullPointerException.class, () -> {
            app.draw();
        });
        assertTrue(true,exception.getMessage());
        

        

        
    }
}
